// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.installation.timestamp", "134236434304161970");
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 169);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1780970182);
user_pref("browser.search.region", "JP");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":24,\"newElementCount\":0}");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "d82ec3ca-0fab-4ae2-92a3-0b97be2669c9");
user_pref("datareporting.dau.cachedUsageProfileID", "ada351cc-6393-4f0a-b74e-8e927b937527");
user_pref("distribution.iniFile.exists.appversion", "151.0.3");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260601110758");
user_pref("extensions.lastAppVersion", "151.0.3");
user_pref("extensions.lastPlatformVersion", "151.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"0a01396d-0cab-45f5-9d06-5c0fa1b53ae2\",\"formautofill@mozilla.org\":\"721e51c3-8ebb-484d-abf9-c795b46bbeec\",\"ipp-activator@mozilla.com\":\"05d60eec-39f5-4538-96b7-bc4267b1b38c\",\"pictureinpicture@mozilla.org\":\"9e69a94f-ad55-4d68-9a0a-a20b0b6c7110\",\"addons-search-detection@mozilla.com\":\"e4514ed7-7e6d-4f9c-a07b-b7d3024b6f50\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"e573c633-49ef-4feb-9555-59aa054f95b5\",\"default-theme@mozilla.org\":\"078b0bf3-a19a-48f9-92a1-05da4fcd5be5\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("media.wmf.media-engine.enabled", 0);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "345fd6e8-57ea-478f-bed9-fecc05bf0e64");
user_pref("pdfjs.enabledCache.state", true);
user_pref("permissions.default.image", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sanity-test.device-id", "0x9bc8");
user_pref("sanity-test.driver-version", "27.20.100.9664");
user_pref("sanity-test.running", true);
user_pref("sanity-test.version", "20260601110758");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1780970180);
user_pref("toolkit.telemetry.cachedClientID", "72cff2b5-a484-4e24-a9e1-fa4d7b11bcf0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "080bd722-6ba7-42b7-99c2-4c99c517abde");
user_pref("toolkit.telemetry.previousBuildID", "20260601110758");
