// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.lastAppBuildId", "20260601110758");
user_pref("extensions.lastAppVersion", "151.0.3");
user_pref("extensions.lastPlatformVersion", "151.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"45ead92b-ef12-430d-a74a-d2b4b0a59316\",\"formautofill@mozilla.org\":\"7cc036c0-d092-41eb-8939-5949d74733c7\",\"ipp-activator@mozilla.com\":\"93841de6-5ae7-4dcb-85a1-866f1bd632e7\",\"pictureinpicture@mozilla.org\":\"70ab1b94-f8d3-4347-b7cc-f51da82b71a0\",\"addons-search-detection@mozilla.com\":\"d0bd408d-b322-4fb3-9da0-a00b418df994\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"6b6eb524-52c1-452a-8ec4-0c4d7f367e5c\"}");
user_pref("media.hardware-video-decoding.failed", false);
user_pref("sanity-test.device-id", "0x9bc8");
user_pref("sanity-test.driver-version", "27.20.100.9664");
user_pref("sanity-test.running", true);
user_pref("sanity-test.version", "20260601110758");
