// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.installation.timestamp", "134236434304161970");
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 169);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1780970071);
user_pref("browser.search.region", "JP");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":24,\"newElementCount\":0}");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "9c5cbf2d-efb8-49c0-8e3e-4a7e3f0bd3bc");
user_pref("datareporting.dau.cachedUsageProfileID", "33adfbd2-f1a8-4ef3-8cfc-d893de799806");
user_pref("distribution.iniFile.exists.appversion", "151.0.3");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260601110758");
user_pref("extensions.lastAppVersion", "151.0.3");
user_pref("extensions.lastPlatformVersion", "151.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"fc07c01f-d408-434d-af57-37424bc6a6b4\",\"formautofill@mozilla.org\":\"dee4f182-354c-44dc-a1ef-0f511c55ccfb\",\"ipp-activator@mozilla.com\":\"2593a2a6-c428-466a-990b-2145f60a9406\",\"pictureinpicture@mozilla.org\":\"968fc64b-d02f-460b-931a-48ac5f3e7628\",\"addons-search-detection@mozilla.com\":\"8c8f2424-b9dd-44cb-9b07-6b1500b60369\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"7a88f5e3-e923-4135-bc6f-f0a836a77ba3\",\"default-theme@mozilla.org\":\"500e521b-37e8-4695-84d5-af4038648c13\"}");
user_pref("layout.css.devPixelsPerPx", "2.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "963c2e6c-774f-4cae-b401-21eac5611445");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sanity-test.device-id", "0x9bc8");
user_pref("sanity-test.driver-version", "27.20.100.9664");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20260601110758");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1780970070);
user_pref("toolkit.telemetry.cachedClientID", "30fc6661-3581-4419-8164-7654a33ff58b");
user_pref("toolkit.telemetry.cachedProfileGroupID", "4466e38a-be6c-4a62-901a-6edb3d1ba7a1");
user_pref("toolkit.telemetry.previousBuildID", "20260601110758");
